### ISSUE TITLE
Double check the results for scheduler plugin

### ISSUE THREAD

**Issue by mkhoshle** [Becksteinlab/scipy_proceedings#14]
@iparask Can you please double check the results from scheduler throughput (Based on this comment: I am somewhat surprised to see the distributed scheduler manage 40,000 tasks per second)? 
Also, we need figures at final size (~2"x 2"), with font size ~10pt so that when we make panels text does not appear to be small (Look at #9).

**Comment by iparask** [comment]
Do you want each figure 2" by 2" or the three figure panel?

**Comment by mkhoshle** [comment]
We want a three figure panel. But we need to make sure that the font will be large enough. In our previous figures font was not large enough. You can make a panel of three 2" by 2" figures.

**Comment by iparask** [comment]
Yes I can.

**Comment by iparask** [comment]
Hello, I committed a figure in the panel folder named [daskThroughputPanel.pdf](https://github.com/Becksteinlab/scipy_proceedings/blob/2017/papers/mahzad_khoslessan/figs/panels/daskThroughputPanel.pdf). Can you please check and tell me if it is according to the style?

**Comment by mkhoshle** [comment]
For some reason when I add the figure to paper it does not compile. When I scale it to 50% it works but still does not look good. With 10% it compiles but it is too small. Did you create this using Inkscape? Also you forgot to add A, B, C for each sub-figure!

**Comment by iparask** [comment]
It does not compile? I created using matplotlib. I will add A,B and C and use Inkscape to create the panel. Let me update it

**Comment by iparask** [comment]
Any better? It actually does not compile with a 40% scale. I am trying to see what is the problem.

**Comment by iparask** [comment]
Hello Mahzad,

please check this [notebook](https://github.com/radical-experiments/midas_exps/blob/master/dask/DaskAnalysisThroughput4.ipynb) and especially the two figures. Tell me how you want to proceed.

Giannis

**Comment by mkhoshle** [comment]
Hi, Thank you! Because the page numbers are already more than 8 (9 with references). I suggest you include the data provided with scheduler plugin only. For details you can point out to the additional data and reference the notebook or wiki in the paper. Please make sure you change xlabel, ylabel, xtick and ytick labelsize. Because the ones you added previously were still small and we had to modify it in Inkscape.

**Comment by iparask** [comment]
Perfect! What fontsize did you use?

**Comment by mkhoshle** [comment]
I used 18!

**Comment by iparask** [comment]
I made a merge error and I reverted it. A [pdf](https://github.com/Becksteinlab/scipy_proceedings/blob/2017/papers/mahzad_khoslessan/figs/panels/daskThroughputPanel.pdf) file with the new panel is in the repo. Please check if the revert is correct and I will commit the correct changes.

I am sorry for the mistake

**Comment by orbeckst** [comment]
Looks good!

**Comment by orbeckst** [comment]
I used your PDF in ec946ff, please check that this looks ok (pdf attached).
[paper.pdf](https://github.com/Becksteinlab/scipy_proceedings/files/1126862/paper.pdf)

**Comment by orbeckst** [comment]
@iparask how many repeats did you run for the scheduler experiments on stampede?

**Comment by iparask** [comment]
@orbeckst, I did 10 repeats per configuration. It looks great!

**Comment by orbeckst** [comment]
Thanks, added to paper. 

--
Oliver Beckstein
email: orbeckst@gmail.com
